// <auto-generated />
using BlazorDataGenerator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorDataGenerator.Migrations
{
    [DbContext(typeof(BDGDbContext))]
    [Migration("20230718143246_initMigration")]
    partial class initMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorDataGenerator.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("Age");

                    b.Property<string>("City")
                        .HasColumnType("character varying")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .HasColumnType("character varying")
                        .HasColumnName("Country");

                    b.Property<string>("Email")
                        .HasColumnType("character varying")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying")
                        .HasColumnName("First_Name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying")
                        .HasColumnName("Last_Name");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("Position");

                    b.Property<int>("Recruitment")
                        .HasColumnType("integer")
                        .HasColumnName("Recruitment");

                    b.Property<int>("Salary")
                        .HasColumnType("integer")
                        .HasColumnName("Salary");

                    b.Property<string>("Street")
                        .HasColumnType("character varying")
                        .HasColumnName("Street");

                    b.HasKey("Id");

                    b.ToTable("Employee", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
